version: '3.8'

services:
  backend:
    image: kartikkumbhar150/hirex_backend:latest
    build:
      context: ./backend
    container_name: hirex_backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env

